In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [5]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)
X_train

741                Yes i will be there. Glad you made it.
5346    My Parents, My Kidz, My Friends n My Colleague...
4317    I can't speak, bcaz mobile have problem. I can...
3963    You have been specially selected to receive a ...
2185    I know a few people I can hit up and fuck to t...
                              ...                        
2170    Shop till u Drop, IS IT YOU, either 10K, 5K, £...
361                Ha ha cool cool chikku chikku:-):-DB-)
2558    This message is brought to you by GMW Ltd. and...
4804                       How do you plan to manage that
3030                What is your record for one night? :)
Name: Message, Length: 4457, dtype: object

In [7]:
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values) 
X_train_cv

<4457x7757 sparse matrix of type '<class 'numpy.int64'>'
	with 58778 stored elements in Compressed Sparse Row format>

In [8]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
X_train_cv.shape

(4457, 7757)

In [10]:
v.get_feature_names_out()[6847]

'theoretically'

In [11]:
v.vocabulary_

{'yes': 7707,
 'will': 7537,
 'be': 1291,
 'there': 6851,
 'glad': 3163,
 'you': 7723,
 'made': 4319,
 'it': 3776,
 'my': 4686,
 'parents': 5098,
 'kidz': 3957,
 'friends': 3018,
 'colleagues': 1897,
 'all': 929,
 'screaming': 5976,
 'surprise': 6642,
 'and': 982,
 'was': 7406,
 'waiting': 7370,
 'on': 4955,
 'the': 6833,
 'sofa': 6293,
 'naked': 4704,
 'can': 1646,
 'speak': 6364,
 'bcaz': 1279,
 'mobile': 4564,
 'have': 3372,
 'problem': 5442,
 'listen': 4163,
 'but': 1595,
 'cann': 1655,
 'voice': 7334,
 'so': 6289,
 'calls': 1637,
 'later': 4046,
 'been': 1314,
 'specially': 6369,
 'selected': 6017,
 'to': 6956,
 'receive': 5633,
 '3000': 439,
 'award': 1190,
 'call': 1623,
 '08712402050': 109,
 'before': 1320,
 'lines': 4148,
 'close': 1856,
 'cost': 2029,
 '10ppm': 275,
 '16': 323,
 'cs': 2104,
 'apply': 1051,
 'ag': 874,
 'promo': 5468,
 'know': 3983,
 'few': 2836,
 'people': 5162,
 'hit': 3458,
 'up': 7208,
 'fuck': 3044,
 'mmmmmm': 4555,
 'love': 4243,
 'much': 4652,
 'ahmad':

In [12]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
np.where(X_train_np[0]!=0)

(array([1291, 3163, 3776, 4319, 6851, 7537, 7707, 7723]),)

In [14]:
# X_train[:4][888] # first 4 sampels

In [15]:
X_train_np[0][1389]

0

In [16]:
# # naive bayes multinomial
# from sklearn.naive_bayes import MultinomialNB

# model = MultinomialNB()
# model.fit()

TF IDF

In [17]:
# Document Frequency (DF) = Number of times term t is present in all docs
# Inverse Document Frequency (IDF) = Total documents / number of documents term i is present in
# Term Frequency (TF) = Total number of time term t is present in doc A / Total number of tokens in doc A
# TF - IDF = TF(t,d) * IDF(t)

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    "Thor eating pizza, Loki is eating pizza, Ironman ate pizza already",
    "Apple is announcing new iphone tomorrow",
    "Tesla is announcing new model-3 tomorrow",
    "Google is announcing new pixel-6 tomorrow",
    "Microsoft is announcing new surface tomorrow",
    "Amazon is announcing new eco-dot tomorrow",
    "I am eating biryani and you are eating grapes"
]

In [19]:
#let's create the vectorizer and fit the corpus and transform them accordingly
v = TfidfVectorizer()
v.fit(corpus)
transform_output = v.transform(corpus)

In [20]:
#let's print the vocabulary

print(v.vocabulary_)

{'thor': 25, 'eating': 10, 'pizza': 22, 'loki': 17, 'is': 16, 'ironman': 15, 'ate': 7, 'already': 0, 'apple': 5, 'announcing': 4, 'new': 20, 'iphone': 14, 'tomorrow': 26, 'tesla': 24, 'model': 19, 'google': 12, 'pixel': 21, 'microsoft': 18, 'surface': 23, 'amazon': 2, 'eco': 11, 'dot': 9, 'am': 1, 'biryani': 8, 'and': 3, 'you': 27, 'are': 6, 'grapes': 13}


In [21]:
#let's print the idf of each word:

all_feature_names = v.get_feature_names_out()
print(all_feature_names)

['already' 'am' 'amazon' 'and' 'announcing' 'apple' 'are' 'ate' 'biryani'
 'dot' 'eating' 'eco' 'google' 'grapes' 'iphone' 'ironman' 'is' 'loki'
 'microsoft' 'model' 'new' 'pixel' 'pizza' 'surface' 'tesla' 'thor'
 'tomorrow' 'you']


In [22]:
for word in all_feature_names:
    
    #let's get the index in the vocabulary
    indx = v.vocabulary_.get(word)
    
    #get the score
    idf_score = v.idf_[indx]
    
    print(f"{word} : {idf_score}")

already : 2.386294361119891
am : 2.386294361119891
amazon : 2.386294361119891
and : 2.386294361119891
announcing : 1.2876820724517808
apple : 2.386294361119891
are : 2.386294361119891
ate : 2.386294361119891
biryani : 2.386294361119891
dot : 2.386294361119891
eating : 1.9808292530117262
eco : 2.386294361119891
google : 2.386294361119891
grapes : 2.386294361119891
iphone : 2.386294361119891
ironman : 2.386294361119891
is : 1.1335313926245225
loki : 2.386294361119891
microsoft : 2.386294361119891
model : 2.386294361119891
new : 1.2876820724517808
pixel : 2.386294361119891
pizza : 2.386294361119891
surface : 2.386294361119891
tesla : 2.386294361119891
thor : 2.386294361119891
tomorrow : 1.2876820724517808
you : 2.386294361119891


In [23]:
corpus[:2]

['Thor eating pizza, Loki is eating pizza, Ironman ate pizza already',
 'Apple is announcing new iphone tomorrow']

In [24]:
transform_output.toarray()[:2]

array([[0.24266547, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.24266547, 0.        , 0.        ,
        0.40286636, 0.        , 0.        , 0.        , 0.        ,
        0.24266547, 0.11527033, 0.24266547, 0.        , 0.        ,
        0.        , 0.        , 0.72799642, 0.        , 0.        ,
        0.24266547, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.30652086,
        0.5680354 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.5680354 ,
        0.        , 0.26982671, 0.        , 0.        , 0.        ,
        0.30652086, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.30652086, 0.        ]])

In [25]:
import pandas as pd

#read the data into a pandas dataframe
df = pd.read_csv("Ecommerce_data.csv")
print(df.shape)
df.head(5)

(24000, 2)


Text                   label
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household
1  Contrast living Wooden Decorative Box,Painted ...               Household
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories

In [26]:
#check the distribution of labels to check imbalance in data
df['label'].value_counts()

label
Household                 6000
Electronics               6000
Clothing & Accessories    6000
Books                     6000
Name: count, dtype: int64

In [27]:
#Add the new column which gives a unique number to each of these labels 

df['label_num'] = df['label'].map({
    'Household' : 0, 
    'Books': 1, 
    'Electronics': 2, 
    'Clothing & Accessories': 3
})

#checking the results 
df.head(5)

Text                   label  \
0  Urban Ladder Eisner Low Back Study-Office Comp...               Household   
1  Contrast living Wooden Decorative Box,Painted ...               Household   
2  IO Crest SY-PCI40010 PCI RAID Host Controller ...             Electronics   
3  ISAKAA Baby Socks from Just Born to 8 Years- P...  Clothing & Accessories   
4  Indira Designer Women's Art Mysore Silk Saree ...  Clothing & Accessories   

   label_num  
0          0  
1          0  
2          2  
3          3  
4          3

In [28]:
#train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df.Text, 
    df.label_num, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.label_num
)

In [29]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)

Shape of X_train:  (19200,)
Shape of X_test:  (4800,)


In [30]:
X_train.head()


15820    IRIS Furniture Children Deluxe Spiderman Toddl...
23224    Godox CB-09 Hard Carrying Storage Suitcase Car...
4638     Ugreen All in 1 USB 3.0 Card Reader USB Memory...
15245    Spread Spain Metallic Gold Bar Trolley/Kitchen...
5378     Chromozome Men's Calf Socks (Pack of 3) (SX-3 ...
Name: Text, dtype: object

In [31]:
print(y_train.value_counts())
print(y_test.value_counts())

label_num
0    4800
2    4800
3    4800
1    4800
Name: count, dtype: int64
label_num
0    1200
2    1200
3    1200
1    1200
Name: count, dtype: int64


In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report

from sklearn.naive_bayes import MultinomialNB


#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),    
     ('Multi NB', MultinomialNB())         
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.96      0.94      1200
           1       0.98      0.92      0.95      1200
           2       0.97      0.97      0.97      1200
           3       0.97      0.99      0.98      1200

    accuracy                           0.96      4800
   macro avg       0.96      0.96      0.96      4800
weighted avg       0.96      0.96      0.96      4800



In [37]:
df = pd.read_csv("Emotion_classify_Data.csv")
print(df.shape)
print(df.head(5))
print(df.value_counts('Emotion'))

(5937, 2)
                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear
Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64


In [40]:
df['Emotion_num'] = df['Emotion'].map({"anger":2,'joy':0,'fear':1})
df

Comment Emotion  Emotion_num
0     i seriously hate one subject to death but now ...    fear            1
1                    im so full of life i feel appalled   anger            2
2     i sit here to write i start to dig out my feel...    fear            1
3     ive been really angry with r and i feel like a...     joy            0
4     i feel suspicious if there is no one outside l...    fear            1
...                                                 ...     ...          ...
5932                 i begun to feel distressed for you    fear            1
5933  i left feeling annoyed and angry thinking that...   anger            2
5934  i were to ever get married i d have everything...     joy            0
5935  i feel reluctant in applying there because i w...    fear            1
5936  i just wanted to apologize to you because i fe...   anger            2

[5937 rows x 3 columns]

In [50]:
X_train, X_test, y_train, y_test = train_test_split(
    df.Comment, 
    df.Emotion_num, 
    test_size=0.2, # 20% samples will go to test dataset
    random_state=2022,
    stratify=df.Emotion_num
)
print(X_train)
print(X_test)
print(X_train.shape)
print(X_test.shape)

4574    i feel so highly intimidated that i get fluste...
2534    i remember feeling a bit confused and really q...
5492    i get out if bed and look in the mirror i feel...
5393    i stopped feeling mad that the machine stole m...
4311    ive been hearing about too many things happeni...
                              ...                        
4718    i often feel so distressed and freaked out whe...
1416    i visited the psychologist all those years ago...
5709    i still feel that way because im stubborn like...
30                 i feel my heart shaky all the time now
3731    i feel strongly that what you identify as the ...
Name: Comment, Length: 4749, dtype: object
1700    i feel for the guy because i think he is since...
2930    i have begun to feel irrationally resentful an...
1951    i taught him what it can look like and how it ...
3224           im feeling so irritable about todays class
3650    i was catapulted back into feeling more terrif...
                             

In [51]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.naive_bayes import MultinomialNB

#1. create a pipeline object
clf = Pipeline([
     ('vectorizer_tfidf',TfidfVectorizer()),    
     ('random forest', RandomForestClassifier())         
])

#2. fit with X_train and y_train
clf.fit(X_train, y_train)


#3. get the predictions for X_test and store it in y_pred
y_pred = clf.predict(X_test)


#4. print the classfication report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92       400
           1       0.91      0.91      0.91       388
           2       0.94      0.86      0.90       400

    accuracy                           0.91      1188
   macro avg       0.91      0.91      0.91      1188
weighted avg       0.91      0.91      0.91      1188



word embedding
word verctor in spacy

In [53]:
import spacy
nlp = spacy.load("en_core_web_lg")

In [58]:
doc = nlp("dog cat banana afskfsd")

for token in doc:
    print(token.text,  "Vector :", token.has_vector, "OOV: ", token.is_oov)

dog Vector : True OOV:  False
cat Vector : True OOV:  False
banana Vector : True OOV:  False
afskfsd Vector : False OOV:  True


In [60]:
base_token = nlp("bread")
base_token.vector.shape

(300,)

In [61]:
doc = nlp("bread sandwich burger car tiger human wheat")

for token in doc:
    print(f"{token.text} <-> {base_token.text}:", token.similarity(base_token))

bread <-> bread: 0.9999999744752309
sandwich <-> bread: 0.6341067010130894
burger <-> bread: 0.47520687769584247
car <-> bread: 0.06451532596945217
tiger <-> bread: 0.04764611675903374
human <-> bread: 0.2151154210812192
wheat <-> bread: 0.615036141030184


In [62]:
def print_similarity(base_word, words_to_compare):
    base_token = nlp(base_word)
    doc = nlp(words_to_compare)
    for token in doc:
        print(f"{token.text} <-> {base_token.text}: ", token.similarity(base_token))

In [63]:
print_similarity("iphone", "apple samsung iphone dog kitten")


apple <-> iphone:  0.4387907401919904
samsung <-> iphone:  0.6708590303423401
iphone <-> iphone:  0.9999999983096304
dog <-> iphone:  0.08211863729338828
kitten <-> iphone:  0.10222317834969896


In [68]:
king = nlp.vocab["king"].vector
man = nlp.vocab["man"].vector
woman = nlp.vocab["woman"].vector
queen = nlp.vocab["queen"].vector

result = king - man + woman

In [69]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([result], [queen])

array([[0.6178014]], dtype=float32)